# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Predict.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1920, 1080)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setStyleSheet("")
        self.Predict_groupBox = QtWidgets.QGroupBox(Dialog)
        self.Predict_groupBox.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.Predict_groupBox.setTitle("")
        self.Predict_groupBox.setObjectName("Predict_groupBox")
        self.widget = QtWidgets.QWidget(self.Predict_groupBox)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.widget.setMouseTracking(False)
        self.widget.setStyleSheet("QWidget#widget{\n"
"    background-color: qlineargradient(spread:pad, x1:0.388, y1:0.250091, x2:1, y2:1, stop:0 rgba(232, 165, 165, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.widget.setObjectName("widget")
        self.radioEntireFolder = QtWidgets.QRadioButton(self.widget)
        self.radioEntireFolder.setGeometry(QtCore.QRect(720, 140, 208, 28))
        self.radioEntireFolder.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioEntireFolder.setStyleSheet("font: 11pt \"Comic Sans MS\";\n"
"")
        self.radioEntireFolder.setObjectName("radioEntireFolder")
        self.radioParticularTrial = QtWidgets.QRadioButton(self.widget)
        self.radioParticularTrial.setGeometry(QtCore.QRect(1160, 140, 221, 28))
        self.radioParticularTrial.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioParticularTrial.setStyleSheet("font: 11pt \"Comic Sans MS\";\n"
"")
        self.radioParticularTrial.setObjectName("radioParticularTrial")
        self.BrowseOptions = QtWidgets.QLabel(self.widget)
        self.BrowseOptions.setGeometry(QtCore.QRect(290, 140, 227, 26))
        self.BrowseOptions.setStyleSheet("font: 11.5pt \"Comic Sans MS\";")
        self.BrowseOptions.setObjectName("BrowseOptions")
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setGeometry(QtCore.QRect(10, -20, 20, 1101))
        self.line.setStyleSheet("color: rgb(0, 0, 0);\n"
"border: 1.5px solid;")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.widget)
        self.line_2.setGeometry(QtCore.QRect(1890, -10, 20, 1091))
        self.line_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"border: 1.5px solid;")
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.widget)
        self.line_3.setGeometry(QtCore.QRect(10, 16, 1901, 20))
        self.line_3.setStyleSheet("color: rgb(0, 0, 0);\n"
"border: 1.5px solid;")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.Title = QtWidgets.QLabel(self.widget)
        self.Title.setGeometry(QtCore.QRect(460, 40, 1041, 91))
        self.Title.setStyleSheet("font: 26pt \"Berlin Sans FB\";\n"
"text-decoration: underline;")
        self.Title.setObjectName("Title")
        self.BrowseText = QtWidgets.QLineEdit(self.widget)
        self.BrowseText.setGeometry(QtCore.QRect(60, 180, 1591, 41))
        self.BrowseText.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.BrowseText.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.BrowseText.setStyleSheet("border: 1.5px solid;\n"
"border-radius: 10px;\n"
"border-color: rgb(14, 6, 111);\n"
"background-color: rgb(165, 200, 255);\n"
"font: 11pt \"Comic Sans MS\";\n"
"")
        self.BrowseText.setAlignment(QtCore.Qt.AlignCenter)
        self.BrowseText.setReadOnly(True)
        self.BrowseText.setObjectName("BrowseText")
        self.BrowseButton = QtWidgets.QPushButton(self.widget)
        self.BrowseButton.setGeometry(QtCore.QRect(1660, 180, 201, 41))
        self.BrowseButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BrowseButton.setStyleSheet("*{\n"
"font: 11pt \"Comic Sans MS\";\n"
"background-color: qradialgradient(spread:pad, cx:0.515, cy:0.489591, radius:1.033, fx:0.251, fy:0.255818, stop:0.338308 rgba(0, 255, 127, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-radius: 20px;\n"
"border: 3px solid;\n"
"border-color: rgb(14, 6, 111);}\n"
"\n"
"*:hover{background-color: #F5DEB3;}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.BrowseButton.setObjectName("BrowseButton")
        self.dial = QtWidgets.QDial(self.widget)
        self.dial.setGeometry(QtCore.QRect(1700, 540, 141, 131))
        font = QtGui.QFont()
        font.setPointSize(1)
        self.dial.setFont(font)
        self.dial.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dial.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.dial.setMaximum(100)
        self.dial.setPageStep(5)
        self.dial.setWrapping(False)
        self.dial.setNotchTarget(1.0)
        self.dial.setNotchesVisible(True)
        self.dial.setObjectName("dial")
        self.progressBar = QtWidgets.QProgressBar(self.widget)
        self.progressBar.setGeometry(QtCore.QRect(60, 230, 1801, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.progressBar.setFont(font)
        self.progressBar.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.progressBar.setStyleSheet("border: 1.5px solid;\n"
"border-radius: 5px;\n"
"border-color: rgb(14, 6, 111);\n"
"background-color: rgb(165, 200, 255);\n"
"font: 9pt \"Comic Sans MS\";")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.graphicsView = QtWidgets.QGraphicsView(self.widget)
        self.graphicsView.setGeometry(QtCore.QRect(60, 270, 1801, 671))
        font = QtGui.QFont()
        font.setPointSize(1)
        self.graphicsView.setFont(font)
        self.graphicsView.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.graphicsView.setStyleSheet("border: 1.5px solid;\n"
"border-radius: 40px;\n"
"border-color: rgb(14, 6, 111);\n"
"background-color: rgb(165, 200, 255);\n"
"")
        self.graphicsView.setObjectName("graphicsView")
        self.Title_2 = QtWidgets.QLabel(self.widget)
        self.Title_2.setGeometry(QtCore.QRect(60, 950, 1801, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Title_2.setFont(font)
        self.Title_2.setStyleSheet("font: 11pt \"Berlin Sans FB\";")
        self.Title_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Title_2.setObjectName("Title_2")
        self.dial_label = QtWidgets.QLabel(self.widget)
        self.dial_label.setGeometry(QtCore.QRect(1710, 660, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.dial_label.setFont(font)
        self.dial_label.setCursor(QtGui.QCursor(QtCore.Qt.UpArrowCursor))
        self.dial_label.setStyleSheet("font: 75 12pt \"Consolas\";")
        self.dial_label.setText("")
        self.dial_label.setAlignment(QtCore.Qt.AlignCenter)
        self.dial_label.setWordWrap(False)
        self.dial_label.setObjectName("dial_label")
        self.webEngineView = QtWebEngineWidgets.QWebEngineView(self.widget)
        self.webEngineView.setGeometry(QtCore.QRect(120, 290, 1571, 631))
        self.webEngineView.setStyleSheet("")
        self.webEngineView.setProperty("url", QtCore.QUrl("about:blank"))
        self.webEngineView.setObjectName("webEngineView")
        self.graphicsView.raise_()
        self.line_3.raise_()
        self.radioEntireFolder.raise_()
        self.radioParticularTrial.raise_()
        self.BrowseOptions.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.Title.raise_()
        self.BrowseText.raise_()
        self.BrowseButton.raise_()
        self.dial.raise_()
        self.progressBar.raise_()
        self.Title_2.raise_()
        self.dial_label.raise_()
        self.webEngineView.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Human-to-Human Interaction Recognizer from WiFi Signal"))
        self.radioEntireFolder.setText(_translate("Dialog", "Classify Entire Folder"))
        self.radioParticularTrial.setText(_translate("Dialog", "Classify Particular Trial"))
        self.BrowseOptions.setText(_translate("Dialog", "Data File Browse Options:"))
        self.Title.setText(_translate("Dialog", "Human-2-Human Interaction Recognizer from WiFi Signal"))
        self.BrowseButton.setText(_translate("Dialog", "Browse"))
        self.dial.setWhatsThis(_translate("Dialog", "For the first-time run of this app, you\'ve to be connected to internet for downloading the requirements of Plotly HTML plot. From next-time, you don\'t need to be online. If anytime you observe blank plot (white-screen), please enable internet connection and run the app.\n"
"\n"
"Roll Mouse Wheel to view different Trial Classifications. If you observe multiple unit jump of Dial-Notch after single Roll of the Mouse Wheel, Change your PC Mouse Wheel Settings: PC Settings > Mouse > Choose how many lines to scroll each time > Set the slider to 1."))
        self.progressBar.setWhatsThis(_translate("Dialog", "Calculation Progress Bar"))
        self.graphicsView.setWhatsThis(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">Classification Plot</span></p></body></html>"))
        self.Title_2.setText(_translate("Dialog", "Copyright ©  2023 | Developed by: Md. Mohi Uddin Khan | Article Authors: Md. Mohi Uddin Khan, Abdullah Bin Shams, Mohsin Sarker Raihan"))
from PyQt5 import QtWebEngineWidgets


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
